apiVersion: batch/v1
kind: Job
metadata:
  name: mattermost-load-test
spec:
  completions: 3
  parallelism: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: mattermost-load-test-container
          image: mattermost/mattermost-loadtest:5.11
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /mattermost-load-test/loadtestconfig.json
            name: loadtestconfig-json
            subPath: loadtestconfig.json
          env:
          - name: MM_CONFIG
            value: "%DATA_SOURCE%"
          command: ["./bin/loadtest", "all"]
      volumes:
        - name: loadtestconfig-json
          configMap:
            name: mattermost-loadtestconfig-json
            items:
            - key: loadtestconfig.json
              path: loadtestconfig.json