apiVersion: mattermost.com/v1alpha1
kind: ClusterInstallation
metadata:
  name: mm-10k
spec:
  ingressName: example.dev.cloud.mattermost.com
  mattermostLicenseSecret: mattermost-license
  replicas: 3
  useServiceLoadBalancer: true
